# Generated by Django 4.2.18 on 2025-01-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the task', max_length=100)),
                ('description', models.TextField(help_text='Description of your task')),
                ('completed', models.BooleanField(default=False, help_text='Is the task open?')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created time')),
            ],
        ),
    ]
